[11.0][MIG] mozaik thesaurus
mozaik-association/mozaik pull request #104
Opened 2018-08-24 22:07 UTC by GillesTephaneMeyomesse

2018-08-27 09:29 UTC, acsonefho requested changes
Few minor changes :)
Enjoy

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/models/abstract_term_finder.py
> +                arg[0], 'in', self.env['thesaurus.term'].browse(
I think this kind of code is hard to read and maintain later. Can you rewrite it to be more understandable please?

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/__manifest__.py
> +# -*- coding: utf-8 -*-
This line is useless in Python3 (all files are already encoded in utf-8).
(Please check also others files).
I think you should update your Pylint (because it should display a message).
@Olivier-LAURENT Travis should display it also no?

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/models/abstract_term_finder.py
> +# -*- coding: utf-8 -*-
Useless coding here too

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/models/res_partner.py
> +# -*- coding: utf-8 -*-
Useless coding here too

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/models/thesaurus.py
> +# -*- coding: utf-8 -*-
Useless coding here too

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +# -*- coding: utf-8 -*-
Useless coding here too

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +            return terms
I think you have an issue here.
You have a return into a loop. So you return only the first terms of children.
I think this code can be re-write like this (please check if it's correct):
return self.mapped("children_ids").get_children_term()

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +                ], limit=80)
Maybe we should use the limit given in parameters?
Is it also possible to put a comment on this function to explain why we're doing this?
Also you forget to add the args into the search domain.
You can search on the Odoo code, they merge 2 domains using "expression.AND(list of domains here)"

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +        for record in self:
Better to let the self.write(vals)

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/tests/test_abstract_term_finder.py
> +# -*- coding: utf-8 -*-
Useless coding here too

2018-08-27 09:29 UTC, acsonefho commented on odoo/addons/mozaik_thesaurus/tests/test_thesaurus.py
> +# -*- coding: utf-8 -*-
Useless coding here too

2018-08-27 10:10 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +                ], limit=80)
@acsonefho ok, I did not think to make an improvement but first migrate but I will correct this

2018-08-27 12:12 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +            return terms
@acsonefho That's not good and raise error i used another way

2018-08-27 12:21 UTC, Olivier-LAURENT requested changes

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/data/data_mail_template.xml
> +        <field name="subject">New thesaurun term created</field>
typo: thesaurun => thesaurus

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/data/thesaurus_data.xml
> +<odoo noupdate="0">
noupdate=1

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/data/data_mail_template.xml
> +<odoo>
noupdate=1

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/data/data_mail_template.xml
> +    <record model="mail.template" id="mozaik_thesaurus_new_term_mail_template">
forcecreate=1

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus.py
> +                    (4, partner_id) for partner_id in follower_ids.mapped(
isn't the default behavior to send to followers when invoking `message_post/message_post_with_template()` ?

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus.py
> +    def notify_follower(self):
I would hope that this should be avoid with a real standard mechanism using `mail.message.subtype.parent_id` field together with an inherit of `_track_subtype()` method. See in hr_recruitement around the subtype `mt_applicant_stage_changed`

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus.py
> +                                raise_if_not_found=False)
leave True here (small probability gracefully to the forcecreate below

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus.py
> +        if not template:
you can remove this unreachable case

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +    _inherit = ['mozaik.abstract.model', 'mail.thread']
`mail.thread` is built-in in `mozaik.abstract.model`

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +    children_ids = fields.Many2many(
child_ids would be better

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +        string='Children Terms',
"Child Terms" would be better

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +        states={'confirm': [('required', True)]},
to remove

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +        required=False,
to remove

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
>      def get_children_term(self):
`_get_children_term()` is better

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
>      @api.constrains('ext_identifier', 'state')
you can remove this constraint

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
>      ext_identifier = fields.Char(
you can remove this field

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/res_groups.xml
> +    <record model="res.groups" id="mozaik_thesaurus_group_user">
thesaurus_user is better

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/res_groups.xml
> +    <record model="res.groups" id="mozaik_thesaurus_group_manager">
thesaurus_manager is better

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/ir.model.access.csv
> +access_thesaurus_term_res_groups_thesaurus_user,thesaurus.term.res.groups.thesaurus.user,model_thesaurus_term,mozaik_thesaurus.mozaik_thesaurus_group_user,1,0,0,0
theasaurus user can write(), and create() terms

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/thesaurus_term_rule.xml
> +        <field name="model_id" ref="base.model_res_partner"/>
res_partner !!?

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/thesaurus_term_rule.xml
> +        <field name="perm_read" eval="1"/>
remove the read permission

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/thesaurus_term_rule.xml
> +        <field name="perm_unlink" eval="1"/>
remove the read and unlink permissions

2018-08-27 12:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/tests/test_abstract_term_finder.py
> +class DummyModel(models.Model):
Is this artifice yet useful since res.partner has now terms directly in this module ?  Thus you can use res.partner as a test model. Correct ?

2018-08-27 12:32 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/tests/test_abstract_term_finder.py
> +class DummyModel(models.Model):
@Olivier-LAURENT this can be useful if we want independent tests and it simulates some model. But i can also use res.partner

2018-08-27 12:49 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/tests/test_abstract_term_finder.py
> +class DummyModel(models.Model):
@GillesTephaneMeyomesse Ok Gilles we keep it.

2018-08-27 13:11 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/models/thesaurus.py
> +                    (4, partner_id) for partner_id in follower_ids.mapped(
@Olivier-LAURENT you think we can just do `message_post_with_template(template_id=template.id,message_type='notification')` i used partner_ids to be sure we send notification for good partners.

2018-08-28 08:55 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/__manifest__.py
> +# -*- coding: utf-8 -*-
@acsonefho Ok that fixed

2018-08-28 09:27 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/models/abstract_term_finder.py
> +                arg[0], 'in', self.env['thesaurus.term'].browse(
@acsonefho small improvement i hope it is more understandable

2018-08-28 10:34 UTC, Olivier-LAURENT requested changes

2018-08-28 10:34 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/abstract_term_finder.py
> +                    domain = expression.AND([
Hi @GillesTephaneMeyomesse 
Do not use here expression.AND, just make: `domain += [(..., ..., ...)]`

2018-08-28 10:34 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/abstract_term_finder.py
> +                    domain = expression.AND([
@GillesTephaneMeyomesse 
Idem just say: `domain += [arg]`

2018-08-28 12:17 UTC, Olivier-LAURENT requested changes

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/data/thesaurus_data.xml
> +        <field name="name">Stage New</field>
New Term to Validate (=> xmlid to change)

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/data/thesaurus_data.xml
> +        <field name="name">Thesaurus Term Stage New</field>
Term to Validate

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/data/thesaurus_data.xml
> +        <field name="parent_id" eval="ref('mozaik_thesaurus.term_stage_new')"/>
just say `ref="term_stage_new"`    (with the new xmlid)

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/data/thesaurus_data.xml
> +    <record id="term_stage_changed" model="mail.message.subtype">
To remove, only one subtype has to make the job

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/data/thesaurus_data.xml
> +    <record id="thesaurus_term_stage_changed" model="mail.message.subtype">
idem

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus.py
> +        track_visibility='onchange'
always end such iteration with a comma

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +        elif 'state' in init_values and record.state == 'confirm':
to remove

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
>      def get_children_term(self):
`_get_child_terms()` is a better name

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
>              name = name.replace('!', '', 1)
`name = name[:-1]`

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> -        args = list(args or [])
`args = args or []`

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +            ], list(args or [])])
just `arg`

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +                ], limit=limit)
`+ args`

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
>              if ids:
why these 2 different methods:
* build domain + call super()
* build domain + call search() + name_get()

Why to not always use the second method ? Otherwise  orm will compute again an extended domain when calling super().

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +        for record in self:
This algorithm differs from the original !  Why having changed it ?
At each record the variable terms is reinitialized !! Producing probably a partial expected result.

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/ir.model.access.csv
> +access_thesaurus_res_groups_thesaurus_user,thesaurus.res.groups.thesaurus.user,model_thesaurus,mozaik_thesaurus.thesaurus_user,1,1,0,0
Previous acl (except groups) were perfect. Why to change them ?

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/res_groups.xml
> +            ref('mozaik_thesaurus.thesaurus_user'),
just `thesaurus_user`

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/res_groups.xml
> -    <record model="res.users" id="base.user_root">
keep this record but ...

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/res_groups.xml
> -            (4, ref('res_groups_archiving_manager')),
... for `thesaurus_manager` !!

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/thesaurus_term_rule.xml
> +        <field name="groups" eval="[(6, 0, [ref('mozaik_thesaurus.thesaurus_user')])]"/>
IMO it is always better to not prefix xmlid when possible (is the case here). In case of refactorisation, code remains valid without migration.

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/security/thesaurus_term_rule.xml
> +        <field name="groups" eval="[(6, 0, [ref('mozaik_thesaurus.thesaurus_manager')])]"/>
idem

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/tests/test_thesaurus.py
> +        self.thesaurus_model.create(
do not create this thesaurus...

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/tests/test_thesaurus.py
> +        self.mail_mail_obj = self.env['mail.mail']
Useful ?

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/tests/test_thesaurus.py
> +        self.demo_user = self.env.ref('base.user_demo')
Useful ?

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/views/thesaurus_term.xml
> +                    <field name="id" invisible="1"/>
IMO useless

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/views/thesaurus_term.xml
> -                        <page string="More Info" name="dev" groups="base.group_erp_manager">
keep this base group here... this must be transparent for end users

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/views/thesaurus_term.xml
> +                    <field name="active" invisible="1"/>
move it visible in the `moreinfo` tab instead

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/views/thesaurus_term.xml
> +                                <field name="thesaurus_id" groups="mozaik_thesaurus.thesaurus_user"/>
move it with groups in `moreinfo` tab and remove the technical page

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/views/thesaurus_term.xml
> +                    <field name="message_follower_ids" widget="mail_followers"/>
keep the original groups here

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/views/thesaurus.xml
> -                    <notebook>
keep this notebook but ...

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/views/thesaurus.xml
> -                            <field name="new_thesaurus_term_id" />
... remove this field.

2018-08-28 12:17 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_thesaurus/views/thesaurus.xml
> +            <form duplicate="0">
this attribute must also be specified in the tree. Just ?

2018-08-28 13:43 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/views/thesaurus.xml
> +            <form duplicate="0">
@Olivier-LAURENT it's not necessary in the list view

2018-08-28 14:32 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
> +        for record in self:
@Olivier-LAURENT it's my fault, no need to change

2018-08-28 15:07 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/security/ir.model.access.csv
> +access_thesaurus_res_groups_thesaurus_user,thesaurus.res.groups.thesaurus.user,model_thesaurus,mozaik_thesaurus.thesaurus_user,1,1,0,0
@Olivier-LAURENT configurator deleted and replaced by manager. i updated previous rights

2018-08-28 15:14 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/models/thesaurus_term.py
>              name = name.replace('!', '', 1)
name[:-1] takes all the elements except the last but in code it is [-1:] just takes last element...

2018-08-28 15:15 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/tests/test_thesaurus.py
> +        self.demo_user = self.env.ref('base.user_demo')
@Olivier-LAURENT forgotten in previous commits

2018-08-28 15:17 UTC, GillesTephaneMeyomesse commented on odoo/addons/mozaik_thesaurus/views/thesaurus.xml
> -                    <notebook>
@Olivier-LAURENT keep without field inside ? There was just `new_thesaurus_term_id`

2018-08-29 13:45 UTC, merged