[MIG] mozaik_membership
mozaik-association/mozaik pull request #116
Opened 2018-09-07 15:21 UTC by RobinetDenisAcsone

2018-09-10 08:42 UTC, acsonefho requested changes
Enjoy :)

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/postal_coordinate.py
> +            self._update_partner_int_instance()
As this IF is the same for create/write, maybe we can group them into 1 function?

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/res_partner.py
>                  lambda s: s.active) or False
For security during the compute, maybe it should be better to take only the first membership_line_ids (to ensure 1 result max).
Because if more than 1 is active = True, it could have an error.
You can import odoo.fields import first
Then: partner.current_membership_line_id = first(current_membership_line_id)
(but we have to remove also the or False on the filtered)

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/res_partner.py
> +            membership_line = partner.membership_line_ids.filtered("active")
Same remark here, maybe use the first(...) to ensure 1 result max (for membership_line)

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/res_users.py
> +        instances = self.env['int.instance'].sudo().search(dom)
I think it could be replaced by (as a special sudo env already exists):
self_sudo.env['int.instance'].search(dom)

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/structure.py
> +class StaAssembly(models.Model):
The class name doesn't match with the python file name

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/structure.py
> +class IntInstance(models.Model):
This class should be extracted from the file I think (1 python file per model)

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/structure.py
> +        return partner_obj.search(domain)
Instead of search (who force a SQL query), it should be better to use the O2M fields (partner_ids) and then a filter (with is_company field). So if the partner is already in the cache, we don't trigger a new SQL query.
And this function is used into a compute function into a loop. So we'll have 1 sql query per record into the self. So I think the filtered is the best solution about perf

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/structure.py
> +            res = self.pool['res.users']._internal_instances()
pool should be replaced by 'env'

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/structure.py
> +class IntAssembly(models.Model):
This class should be into another python file

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/structure.py
>              vals.update({'int_instance_id': vals['instance_id']})
As this if is the same into create and write, maybe it could be extracted into a same function

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/structure.py
> +class ExtAssembly(models.Model):
Same here: class should be extracted into a new python file

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/structure.py
>          if 'instance_id' in vals:
This if is quite similar for few models. Maybe we can create an abstract model who is doing this if for every create/write.
@Olivier-LAURENT what do you think? Bad/good idea, without increase the complexity and understanding?

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/virtual_models.py
> +class VirtualMasterPartner(models.Model):
File name doesn't match with the model/class name

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/models/virtual_models.py
> +class VirtualCustomPartner(models.Model):
This model should be extracted (1 file per model)

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/tests/test_force_int_instance.py
> +# Copyright 2017 ACSONE SA/NV
Replace 2017 per 2018

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/tests/test_postal_coordinate.py
> +        postal_coordinates = self.env["postal.coordinate"]
Don't forget the ".browse()" on this line to avoid mix between "models" and recordset

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/tests/test_postal_coordinate.py
> +        partners = self.env["res.partner"]
Same remark here, add ".browse()"

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/tests/test_res_partner.py
>          return self.partner_obj.browse(self.cr, self.uid, partner_id)
Should be replaced with new API (or maybe delete this function if not used anymore)

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/tests/test_structure.py
> +        # instance_id = self.env.ref('mozaik_structure.sta_instance_03')
Maybe could be removed

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/views/res_partner.xml
> +            <!--<xpath expr="//header/div/button[@name='action_invalidate']" position="after">-->
Maybe could be removed?

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/wizards/change_main_address.py
> +        if not self.old_int_instance_id:
I think this old_int_instance_id field is only used for the onchange, to know if the int_instance_id has been updated from the original value (so the value into the DB).
If it's the case, we can remove this field, because into the onchange, we can have access to the real value (into DB) and check if the value is different that the "onchange value".
@Olivier-LAURENT Maybe you can answer to this question, about the real utility of this "old" field.

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/wizards/generate_reference.py
> +                [('membership_state_id.code', '=', 'member'),
Maybe we can use a O2M field with a filtered? To avoid SQL query?

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/wizards/generate_reference.py
> +                [('membership_state_id.code', '=', 'member_candidate'),
Same remark here

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/wizards/generate_reference.py
> +                 ('id', 'in', partner_ids)])
Same remark here again

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/wizards/generate_reference.py
> +                self.with_delay().generate_reference_action(
Could be useful to add a  little description (with description parameter) into the with_delay() to know exactly what does the new job

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/wizards/pass_former_member.py
>              domain = [('id', 'in', partner_ids), ('reference', '!=', False)]
We can have an issue here.
Because few lines before, partner_ids could be a recordset or a list of int.
If partner_ids is a recordset, the search will raise an exception because it need list of int.
I think the line 32 (partner_ids = partner_obj.search(active_domain)) should be replaced by a filtered. And do the search into the elif with the active_ids.

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/wizards/pass_former_member.py
> +            date_ok = curr_month in AVAILABLE_MONTHS
Maybe we can put AVAILABLE_MONTHS into a function (with api.model) to avoid global variables.

2018-09-10 08:42 UTC, acsonefho commented on odoo/addons/mozaik_membership/wizards/pass_former_member.py
> +        partners = self.env["res.partner"].search(domain)
Maybe better to use filtered here too to avoid SQL query

2018-09-10 12:29 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_membership/wizards/generate_reference.py
> +                [('membership_state_id.code', '=', 'member'),
O2M isn't possible (api.model) but a filtered is now used.

2018-09-10 14:08 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_membership/wizards/change_main_address.py
> +        if not self.old_int_instance_id:
```old_int_instance_id``` is the instance of the partner, if we remove it from the wizard, we need to add a relation to the partner or retrieved this partner from the context

2018-09-11 13:12 UTC, Olivier-LAURENT requested changes

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/int_instance.py
> +                p.int_instance_id == s.id and not p.is_company))
Is this lambda really valid ?  ... you compare recordset against id .... and `s` is not defined ... I propose:
`lambda s, ii=inst: s.int_instance_id == ii and not s.is_company`

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/abstract_coordinate.py
> +        res.sudo()._update_followers()
Shouldn't this method also called from `write()` ?  What about the followers after a change of the int_instance_id of the partner ?

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/int_instance.py
> +    def check_mail_message_access(self, res_ids, operation, model_name=None):
In which case this method is useful ? Without answer I suggest to remove it. If any, later, we will find the appropriate solution.

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/int_instance.py
> +            if self.env.uid != SUPERUSER_ID:
`if not self.env.user.is_admin()`

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/int_instance.py
> +            res = self.env['res.users']._internal_instances()
it would be better to make `first()` here...

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/int_instance.py
> +        return first(res)
... and not here !

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/postal_coordinate.py
>                  zip_id = pc.address_id.address_local_zip_id
`city_id` ??

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/postal_coordinate.py
>          Update instance of partner linked to the postal coordinate case where
Rewording...
Update instance of partner linked to the postal coordinate
when it becomes main and its `active` field is equal to the `active` field of its partner.
Instance is the default one if no instance found on the city

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/postal_coordinate.py
>                      zip_id and zip_id.int_instance_id.id or \
remove `.id`

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/postal_coordinate.py
>          call `_update_partner_int_instance` if `is_main` is True
Compute followers and change partner instance if any

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/postal_coordinate.py
> +        self_ctx = self.with_context(delay_notification=change_instance)
This context is unused in this addon. I suggest to remove it here.

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/postal_coordinate.py
>          call `_update_partner_int_instance` if `is_main` is True
Recompute followers and change partner instance if any

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_partner.py
> +        for val in self:
`val` is no longer an appropriate name now

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_partner.py
> +            partner.message_subscribe(fol_ids.ids)
`partner_ids=...`

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_partner.py
>              # when creating the workflow and updating the first time
this comment seems out-of-date (regarding workflow)
I suggest report this business rule in the default property of the field `membership_state_id`

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_partner.py
> +        if 'identifier' in vals and res.identifier > 0:
remove the `and res.identifier > 0` part of the expression together with the following comment (it was a legacy rule)

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_partner.py
> +    def _subscribe_assemblies(self, int_instance_id=None):
Is this method still called ? However, it is this method that subscribes followers on partners... ?

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_partner.py
> +            p_upd_fol.sudo()._update_followers()
It appears all these kind of calls use sudo(), here and in coordinates. The real leagcy reason is the reading of instances "above" the level of the user (in the instances pyramid). Thus, (maybe), it would be better to improve this by sudoing the reading method (located in mozaik_strcture/int_instance.py), and leaving all `_update_followers()` call without invoking `sudo()`. What do you think ?

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_partner.py
> +        if not self.env.context.get('lang'):
legacy check ... because workflow didn't propagate context... IMO no more useful

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_partner.py
> +    def update_state(self, membership_state_code):
_update_state()

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_partner.py
> +            vals['del_doc_date'] = False
Is this field still exist ?

2018-09-11 13:12 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership/models/res_users.py
> +    lang = fields.Selection(related='partner_id.lang')
Who does really use this field ?

2018-09-12 09:27 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_membership/models/res_partner.py
> +            p_upd_fol.sudo()._update_followers()
I'm agreed, changed

2018-09-12 10:20 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_membership/models/int_instance.py
> +    def check_mail_message_access(self, res_ids, operation, model_name=None):
I didn't find it useful, removed

2018-09-17 08:04 UTC, merged