[ADD] Add first bounce field and modify reset failed button to reset …
mozaik-association/mozaik pull request #142
Opened 2019-01-28 14:26 UTC by EcoloDevelopper

Add first bounce field and modify reset failed button to reset first bounce field too; refs #30075

2019-01-28 20:39 UTC, Olivier-LAURENT requested changes
In addition, test in `test_bounce.py` must be completed.

It would be also nice to fix the `test_legislature_early_closing` test making travis unhappy !

2019-01-28 20:39 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/abstract_coordinate.py
> +                   },context=context)
this comma must be followed by a space

2019-10-07 18:11 UTC, Olivier-LAURENT requested changes

2019-10-07 18:11 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +            '2019-09-10 00:00:00')
This third (and optional parameter) is not useful. For me you can remove it.

2019-10-07 18:11 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertFalse(bc['bounce_counter'], 'Reset counter fails with wrong bounce_counter')
Idem. you can remove this second parameter.

2019-10-07 18:11 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertEqual(bc['first_bounce_date'], False)
Replace this assertEqual by a assertFalse

2019-10-07 18:11 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +            'date': FIRSTBOUNCEDATE
There is no field date defined in this wizard. To remove.

2019-10-07 18:11 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/abstract_coordinate.py
> +                    'first_bounce_date': False
Should'nt be bounce_date also reset ?

2019-10-07 18:11 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +            coord['first_bounce_date'], FIRSTBOUNCEDATE,
It will never true ! Compare it instead to coord['bounce_date'] they must be equal.

2019-10-07 18:11 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
>          bc = self.model_coordinate.read(
Better to use a browse here instead of a read... code more clear finally

2019-10-07 18:11 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertEqual(bc['first_bounce_date'], False)
You can also check for bounce_date here, it also must be False

2019-10-07 18:11 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/abstract_coordinate.py
> +            'First Failure Date', track_visibility='onchange')
always better to end list with a comma to avoid later the delete/insert effect as 3 lines hereabove

2019-10-14 10:49 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/abstract_coordinate.py
> +                   },context=context)
Done

2019-10-14 10:49 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +            '2019-09-10 00:00:00')
Done

2019-10-14 10:50 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertEqual(bc['first_bounce_date'], False)
Done

2019-10-14 10:50 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/abstract_coordinate.py
> +                    'first_bounce_date': False
forgot to add it, I correct it.

2019-10-14 10:51 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
>          bc = self.model_coordinate.read(
I change the test with read method.

2019-10-14 10:51 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/abstract_coordinate.py
> +            'First Failure Date', track_visibility='onchange')
Done

2019-10-15 16:29 UTC, Olivier-LAURENT requested changes

2019-10-15 16:29 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        bc = self.model_coordinate.browse(
`bc` is now an inappropriate variable name. Name it `coord`, it will be ruse hereafter.

2019-10-15 16:29 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        coord = self.model_coordinate.browse(
This `coord` is the same browse record as previous `bc`. The cahe will make the job. Remove this re-browsing.

2019-10-15 16:29 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
>              'Update coordinate fails with wrong bounce_counter')
Remove ALL these steril failing description in all your `assert*()` calls. No added value.

2019-10-15 16:29 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertEqual(bc.first_bounce_date, bc.bounce_date)
Special but correct ! Only because bc==coord !!

2019-10-15 16:29 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        bc = self.model_coordinate.browse(
Remove this re-browsing

2019-10-15 16:29 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +FIRSTBOUNCEDATE = '2019-09-10 00:00:00'
Useless. To remove.

2019-10-15 16:41 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/abstract_coordinate.py
> +    def copy(self, cr, uid, ids, default=None, context=None):
I don't understand this difference (nor the following one) !

2019-10-16 12:06 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/abstract_coordinate.py
> +    def copy(self, cr, uid, ids, default=None, context=None):
I don't understand why it considered has a changement I didn't touch this.

2019-10-16 12:06 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +FIRSTBOUNCEDATE = '2019-09-10 00:00:00'
Done

2019-10-16 12:07 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertEqual(bc.first_bounce_date, bc.bounce_date)
Done

2019-10-16 12:07 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
>              'Update coordinate fails with wrong bounce_counter')
Done

2019-10-16 12:07 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        coord = self.model_coordinate.browse(
Done

2019-10-16 12:07 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        bc = self.model_coordinate.browse(
Done

2019-10-16 12:33 UTC, Olivier-LAURENT requested changes

2019-10-16 12:33 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertFalse(coord.bounce_counter, '')
Remove = Supprimer ! ... Just say `self.assertFalse(coord.bounce_counter)`

2019-10-16 12:33 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +            '')
idem

2019-10-16 12:33 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +            'Bad Coordinate')
Idem

2019-10-16 12:33 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertFalse(coord.bounce_counter, '')
Idem

2019-10-16 12:33 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertFalse(coord.bounce_date, False)
Idem

2019-10-16 12:33 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertFalse(coord.first_bounce_date, False)
Idem

2019-10-16 17:25 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertFalse(coord.bounce_counter, '')
My bad. it's done.

2019-10-16 17:27 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +            '')
Done

2019-10-16 17:27 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertFalse(coord.bounce_counter, '')
Done

2019-10-16 17:28 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertFalse(coord.bounce_date, False)
Done

2019-10-16 17:28 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +        self.assertFalse(coord.first_bounce_date, False)
Done

2019-10-16 17:28 UTC, EcoloDevelopper commented on odoo_addons/mozaik_coordinate/tests/test_bounce.py
> +            'Bad Coordinate')
Done

2019-10-22 13:32 UTC, merged