[WIP][MIG] migrate mozaik_mandate (minus committee and candidate, unmigrat…
mozaik-association/mozaik pull request #145
Opened 2019-01-30 09:35 UTC by RobinetDenisAcsone

…ed in mozaik_committee)

2019-04-15 16:26 UTC, Olivier-LAURENT requested changes
TBC from  odoo/addons/mozaik_mandate/models/mandate_category.py

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik/__manifest__.py
> +        'mozaik_virtual_partner_instance',
Sure ? Most probably you meant `mozaik_virtual_partner_mandate` !

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +    is_submission_mandate = fields.Boolean(
Small refactorisation please: => with_revenue_declaration

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +        string='With Wages Declaration',
thus useless

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +        help='Submission to a Mandates and Wages Declaration',
Representative is subject to a declaration of income

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +    is_submission_assets = fields.Boolean(
with_assets_declaration

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +        string='With Assets Declaration',
thus useless

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +        help='Submission to a Mandates and Assets Declaration',
Representative is subject to a declaration of assets

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +        readonly=True)
Also need to repeat readonly ?

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +        track_visibility='onchange')
Need to repeat readonly and track_vivibility ?

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +            mandates = self.search(args, limit=limit)
Why to not return super() in this case ?

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +        Invalidates mandates at the current date
Invalidate mandates

Use current date if no date is given

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +            if end_date >= mandate.deadline_date:
just `>`

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +            if end_date <= mandate.start_date:
just `<`

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +                vals={'end_date': end_date})
Other keys in initial `vals` are unused here !

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +        ===========================
remove this =====

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/abstract_mandate.py
> +        ======================================
id.

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/ext_mandate.py
> +    _allowed_inactive_link_models = ['ext.candidature']
ext.candidature ?

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/ext_mandate.py
> +
From here, sure that all of these fields and/or properties must be entirely redefined ?

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/ext_mandate.py
> +    def onchange_mandate_category_id(self):
`_onchange_mandate_category_id`

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/ext_mandate.py
> +    def onchange_ext_assembly_id(self):
`_onchange_ext_assembly_id`

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/generic_mandate.py
>          ======
remove this =======

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/generic_mandate.py
> +        model, m_id = self.mandate_ref.split(',')
`ensure_one()`   ?

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/int_instance.py
> +            [assembly.id for assembly in assembly_obj.search(domain)]
`assembly_obj.search(domain).ids`    ??

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/int_instance.py
> +            [object_ids.id for object_ids in model_obj.search(domain)]
`model_obj.search(domain).ids`   ??

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/int_instance.py
> +        compute='_compute_mandate_count', type='integer',
remove this `type` property on these all 3 fields

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/int_mandate.py
> +    def onchange_mandate_category_id(self):
better with an undescore

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/int_mandate.py
> +    _allowed_inactive_link_models = ['int.candidature']
Same as above

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/int_mandate.py
> +
Same as above about fields/properties

2019-04-15 16:26 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/int_mandate.py
> +    def onchange_int_assembly_id(self):
better with an undescore

2019-04-16 16:19 UTC, Olivier-LAURENT requested changes

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/generic_mandate.py
> +    mandate_ref = fields.Selection(
Why to use the type `Selection` ? Just `Char` would make the job, no ?

Legacy type `Reference` requested such a selection, but from now ...

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/mandate_category.py
> +        string='Exclusive Category')
Exclusive Categories

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/mandate_category.py
> +        help='Submission to a Mandates and Wages Declaration',
Representative is subject to a declaration of income

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/mandate_category.py
> +        help='Submission to a Mandates and Assets Declaration',
Representative is subject to a declaration of assets

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/mandate_category.py
> +                           for record in category.exclusive_category_m2m_ids]
What about `category.exclusive_category_m2m_ids.ids` ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/mandate_category.py
> +        ==============================
remove this =====...

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/mandate_category.py
> +    def _check_exclusive_consistency(
Complicated !

Why not enter here (`_update_exclusive_inverse_relation()` with `ensure_one()`) with just previous and new resordset of exclusive categories, then to compute the inverse recordset to `write()` with magic number 4 and another recordset to `write()` with magic number 3.

Just atomize the initial `write()` if it contains `exclusive_category_m2m_ids` field.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/res_partner.py
> +        prefix = 'ext'
useful such indirection ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/res_partner.py
> +        string='External Assemblies', compute='_compute_assembly_count')
These 2 computes methods (for unstore fileds) share partially the same code, i.e. `_get_assemblies()`. It would be better to group them into a single method....

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/res_partner.py
> +    def _get_mandates(self):
... and to move this method in `ext.assembly` model removing the ensure_one() restriction

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/sta_mandate.py
> +        self.sta_power_level_id = sta_power_level_id
This field is a related !?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/security/ir.model.access.csv
> +access_generic_mandate_res_group_mandate_user,mozaik.generic.mandate.res.group.user,model_generic_mandate,mozaik_mandate.res_groups_mandate_user,1,0,0,0
Add a newline

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/ext_mandate.xml
> +                    <separator string="Remits"/>
Why `Remits` ?    I suggest no separator.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/ext_assembly_category.xml
> +                           readonly="1" context="{'default_mandate_category_id': active_id}">
Is this context useful ? ... the field is readonly.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/ext_assembly_category.xml
> +                <page name="mandate categories" string="Mandate Categories">
s/mandate categories/mandate_categories/

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/ext_assembly_category.xml
> +                           readonly="1"               context="{'default_mandate_category_id': active_id}">
Readonly ! Sure ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/generic_mandate.xml
> +            <form edit="0" create="0" delete="0" string="Incompatible Mandate">
remove string

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/generic_mandate.xml
> +            <search string="Incompatible Mandates">
id.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/generic_mandate.xml
> +                <group expand="0" string="Group By..." name="group_by">
only name is useful now

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/models/int_instance.py
> +        model = context.get('model')
this model thru the `context` seems to be redundant ... once the action is fetched, this is the value of the `res_model` field

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/int_instance.xml
> +                    context="{'action': 'mozaik_mandate.sta_mandate_action', 'model': 'sta.mandate'}"
see above about the `model` context key

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/int_instance.xml
> +                    context="{'action': 'mozaik_mandate.ext_mandate_action', 'model': 'ext.mandate'}"
id.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/int_instance.xml
> +                    context="{'action': 'mozaik_mandate.int_mandate_action', 'model': 'int.mandate'}"
id.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/legislature.xml
> +                                'default_legislature_id': active_id}" />
Is `default_xxx` when `search_default_xxx` is specified ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/mandate_category.xml
> +                <filter name="with_revenue_declaration" string="Wage Declaration"
With revenue declaration   ... to gain some translations ;-)

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/mandate_category.xml
> +                <filter name="with_assets_declaration" string="Assets Declaration"
With assets declaration

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/mandate_category.xml
> +            <search string="Mandate Categories">
remove string

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/mandate_category.xml
> +            <form string="Mandate Category">
remove string

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/mandate_category.xml
> +                <field name="type" invisible="1"/>
Useful this hidden `type` ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/mandate_category.xml
> +        <field name="name">State Categories</field>
I would say instead: "For State Mandates"

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/mandate_category.xml
> +        <field name="name">Internal Categories</field>
For Internal Mandates

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/mandate_category.xml
> +        <field name="name">External Categories</field>
For External Mandates

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/menus.xml
> +        <field name="groups_id" eval="[(6, 0, [ref('mozaik_mandate.res_groups_mandate_user')])]" />
I would say `manager` here

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/menus.xml
> +        <field name="sequence" eval="30"/>
This app is intended for mandate users

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/sta_assembly_category.xml
> +                           readonly="1" context="{'default_mandate_category_id': active_id}">
useless context

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/sta_assembly_category.xml
> +                           readonly="1" context="{'default_mandate_category_id': active_id}">
Why readonly ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/views/sta_mandate.xml
> +                    <separator string="Remits"/>
remove this separator

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.py
> +        ondelete='cascade')
only useful if the field is required

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.py
> +        ondelete='cascade')
why not a related not strored from `mandate_id.mandate_category_id` ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.py
> +        ondelete='cascade')
only useful for required m2o

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.py
> +        ondelete='cascade')
why not a related not stored from `mandate_id.partner_id` ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.py
> +        ondelete='cascade')
why not a related not stored from `assembly_id.partner_id` ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.py
> +            if action == 'renew':
else:

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.py
> +        ====================
remove this ====

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.py
> +        ===========
Id.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.py
> +        ===========
Id.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.xml
> +            <form string="Mandate">
remove string

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_copy_mandate_wizard.xml
> +                   <separator string="Add Complementary Mandate"/>
Add New Mandate

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_update_mandate_end_date_wizard.py
> +                                   ' by setting end date !')
... its end date

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_update_mandate_end_date_wizard.py
> +                                   ' anymore!')
is no longer active

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_update_mandate_end_date_wizard.py
> +                                   ' anymore!')
...is no longer active

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_update_mandate_end_date_wizard.py
> +                                   ' anymore!')
...is no longer active

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/abstract_update_mandate_end_date_wizard.xml
> +            <form string="Set end date">
remove string

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/allow_incompatible_mandate_wizard.xml
> +        <field name="name">Allow Incompatible Mandate</field>
... Mandates

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/copy_ext_mandate_wizard.xml
> +        <field name="name">Duplicate</field>
Duplicate Mandate

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/copy_int_mandate_wizard.py
> +    mandate_id = fields.Many2one(
IMO all of these cascades are useless, except for new_assembly_id 

And readonly properties are redundant with the abstract model

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/copy_ext_mandate_wizard.py
> +    mandate_id = fields.Many2one(
IMO all of these cascades are useless, except for new_assembly_id 

And readonly properties are redundant with the abstract model

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/copy_int_mandate_wizard.xml
> +        <field name="name">Duplicate</field>
Duplicate Mandate

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/copy_sta_mandate_wizard.py
> +    mandate_id = fields.Many2one(
IMO all of these cascades are useless, except for new_assembly_id 

And readonly properties are redundant with the abstract model

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/copy_sta_mandate_wizard.py
> +        ====================
to remove

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/copy_sta_mandate_wizard.xml
> +        <field name="name">Duplicate</field>
Duplicate Mandate

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/update_ext_mandate_end_date_wizard.py
> +                res['message'] = _('The assembly is not active'
Assembly is no longer active

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/update_ext_mandate_end_date_wizard.py
> +        mandate = self.env[model].browse(ids[0])
only useful in the following `if`

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/update_int_mandate_end_date_wizard.py
> +        mandate = self.env[model].browse(ids[0])
Same as above

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/update_int_mandate_end_date_wizard.py
> +                res['message'] = _('The assembly is not active anymore!')
Same as above

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/update_sta_mandate_end_date_wizard.py
> +        readonly=True)
redundant string and readonly  properties ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership_mandate/models/ext_mandate.py
> +    partner_instance_ids = fields.Many2many(
Cannot be specified in abstract.mandate model ?

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership_mandate/models/ext_mandate.py
> +        string='Partner Internal Instance',
...Instances

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership_mandate/models/generic_mandate.py
> +        string='Partner Internal Instance')
...Instances

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership_mandate/models/generic_mandate.py
> +    partner_instance_ids = fields.Many2many(
Id.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_membership_mandate/models/sta_mandate.py
> +    partner_instance_ids = fields.Many2many(
Id.

2019-04-16 16:19 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_virtual_partner_mandate/views/virtual_partner_mandate.xml
> +                <group expand="0" string="Group By..." name="group_by">
only attribute name is yet relevant

2019-04-17 09:13 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_mandate/wizards/copy_int_mandate_wizard.py
> +    mandate_id = fields.Many2one(
Why it's not useless for new_assembly_id? it's also not required.

2019-04-17 09:21 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_mandate/wizards/copy_int_mandate_wizard.py
> +    mandate_id = fields.Many2one(
Right ! If the field is not required, the cascade is useless.

2019-04-17 09:59 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_mandate/views/legislature.xml
> +                                'default_legislature_id': active_id}" />
True, `default_xxx` is not needed

2019-04-17 13:15 UTC, merged