27745 add other gender ara
mozaik-association/mozaik pull request #174
Opened 2019-11-07 11:10 UTC by EcoloDevelopper

Add "other" Gender

2019-11-07 12:22 UTC, Olivier-LAURENT requested changes
Currently a lot of filters in search views filter on gender=='m' or gender=='f'. IMO this new value should come with such new filters in all these models (partner, virtual models)

2019-11-07 12:43 UTC, Olivier-LAURENT requested changes

2019-11-07 12:43 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_person/res_partner.py
> +    ('o', 'Other'),
It would be better to define this new value as this: `('other', 'Other')`. Because in V11, this custom definition of gender has been replaced by an OCA module (i.e. [partner-contact-gender](https://github.com/OCA/partner-contact/tree/11.0/partner_contact_gender)) in which this third choice is such defined.

2019-12-05 14:24 UTC, Olivier-LAURENT requested changes
Futhermore, but only FYI, the changes of translations of "terms" 2018, 2019, ... come from a bug in the specification of the `reference_date` field in the `generate_reference` wizard. The selection method, i.e. `get_year_selection` should be specified without its `()`.

2019-12-05 14:24 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_communication/views/virtual_models_view.xml
> +                        domain="[('gender','=','o')]" />
This new filter should not come with a new `<separator />`. Instead it must be enclosed with the previous  "filters group" Male/Female to avoid that it produces a new "group" by itself.

Also a reminder about a previous remark here below: have a look at https://github.com/mozaik-association/mozaik/pull/174#discussion_r343629964

2019-12-05 14:24 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_person/res_partner_view.xml
> +                    <field name="partner_involvement_ids"/>
This kind of revision is very strange (also for most subsequent revisions). Sure that you does not introduce tabs or leading blanks in your branch about this file ?

2019-12-06 10:16 UTC, EcoloDevelopper commented on odoo_addons/mozaik_communication/views/virtual_models_view.xml
> +                        domain="[('gender','=','o')]" />
My bad, it's a mistake.

2019-12-06 10:21 UTC, EcoloDevelopper commented on odoo_addons/mozaik_person/res_partner_view.xml
> +                    <field name="partner_involvement_ids"/>
To be honest I don't have any idea how I introduce this modification. I will be more vigilant when I commit code. I see the difference it's that there is one white space remove at the end of the line.

2019-12-06 11:22 UTC, Olivier-LAURENT requested changes

2019-12-06 11:22 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_communication/views/virtual_models_view.xml
> +                    <filter string="Volunteer"  name="volunteer"
Another useless modification. Don't hesitate to review your own modifications before commiting/pushing... `git diff` can avoid such unexpected alteration.

2019-12-06 11:22 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_person/res_partner_view.xml
> +                    <filter string="Other" name="other" domain="[('gender','=','o')]" invisible="'default_is_company' not in context or context.get('default_is_company')"/>
s/o/other/

2019-12-09 13:47 UTC, EcoloDevelopper commented on odoo_addons/mozaik_communication/views/virtual_models_view.xml
> +                    <filter string="Volunteer"  name="volunteer"
I correct it, thanks for the advice.

2019-12-16 15:16 UTC, merged