[ADD] mozaik_mass_mailing_automation
mozaik-association/mozaik pull request #254
Opened 2021-10-20 08:45 UTC by marielejeune

refs #53576

2021-10-20 08:49 UTC, marielejeune commented
@qgroulard review requested

2021-10-25 08:40 UTC, qgroulard requested changes

2021-10-25 08:40 UTC, qgroulard commented on mozaik_mass_mailing_automation/models/mailing_mailing.py
> +    def _compute_schedule_date(self):
compute must always set a value, otherwise the field's value will be set to None.
If I understand correctly you need an extra
```
else:
    record.schedule_date = record.schedule_date
```

Please test this case (and other cases) as codecov suggests it.

2021-10-25 08:40 UTC, qgroulard commented on mozaik_mass_mailing_automation/models/mailing_mailing.py
> +    )  # becomes a compute in case of automation
Confusing comment imo.
I think the `_compute_schedule_date()` method is simple enough to easily understand how this field works.

In the other hand, you may want to help users understand this field by adding a description.

2021-10-25 08:40 UTC, qgroulard commented on mozaik_mass_mailing_automation/models/mailing_mailing.py
> +                {"next_execution": mailing.next_execution + relativedelta(days=1)}
What if mailing.next_execution = False ?

2021-10-25 08:40 UTC, qgroulard commented on mozaik_mass_mailing_automation/models/mailing_mailing.py
> +        default=datetime.now(),
Default value seems dangerous to me.
It means that from now on every `mailing.mailing` will have a `next_execution` field filled.
I think scheduling a next_execution should always be done on purpose by a user.

Maybe I'm wrong ? You surely better know the use case than me.

PS: If you are aiming to ease encoding, you can add default in the view rather than in the model.

2021-10-25 15:42 UTC, marielejeune commented on mozaik_mass_mailing_automation/models/mailing_mailing.py
> +    )  # becomes a compute in case of automation
This field won't be displayed.

2021-10-26 07:48 UTC, marielejeune commented on mozaik_mass_mailing_automation/models/mailing_mailing.py
> +                {"next_execution": mailing.next_execution + relativedelta(days=1)}
Can't happen (api.constraint) when mailing.automation = True

2021-10-27 08:31 UTC, merged