[CHG] Create A/B mechanism for distribution lists
mozaik-association/mozaik pull request #59
Opened 2018-04-20 09:17 UTC by andreparames

refs #28891

2018-04-23 21:31 UTC, Olivier-LAURENT requested changes
hi @andreparames 
thx for the job... only a few comments

2018-04-23 21:31 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_communication/wizard/distribution_list_mass_function.py
> +                    if wizard.contact_ab_pc < 100:
From the second batch, if user specify 100%, this condition is evaluated to False. It would be safer to say:
`if wizard.contact_ab_pc < 100 or context.get('mailing_group_id'):`

2018-04-23 21:31 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_communication/mass_mailing.py
>      _columns = {
Entire class MassMailing here must be removed (its a duplicate of your new file  odoo_addons/mozaik_communication/models/mail_mass_mailing.py)

2018-04-23 21:31 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_communication/models/mail_mass_mailing.py
> +                if mailing.contact_ab_pc < 100 and mailing.group_id:
As soon as a mass mailing is created with a group, this condition must be True. Thus it is better to say here:
`if mailing.contact_ab_pc < 100 or mailing.group_id:`
see also the related comment in the mass function wizard below

2018-04-23 21:31 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_communication/models/mass_mailing_report.py
> +    _auto = False
Does this property need to be re-specified here?

2018-04-23 21:31 UTC, Olivier-LAURENT commented on odoo_addons/mozaik_communication/models/mail_mass_mailing.py
> +        'mail.mass_mailing.group', copy=True)
a string property is needed here because it is possible to request an advanced "group by" from the searchbox

2018-04-24 07:28 UTC, andreparames commented
Thanks for the review! I've made the suggested changes.

2018-04-26 20:27 UTC, Olivier-LAURENT approved these changes

2018-04-27 09:36 UTC, merged