[ADD] mozaik_sponsorship
mozaik-association/mozaik pull request #717
Opened 2023-03-23 10:49 UTC by marielejeune

refs #67035

2023-03-24 16:16 UTC, marielejeune commented on mozaik_membership_request/wizards/add_membership.py
> +    def _create_membership_line(self, reference=None):
@RobinetDenisAcsone what do you think of the following improvement? Do you see any potential problems?

When paying a membership line, the `mark_as_paid` workflow checks the statechart and creates the following membership line, if there is a transition with `event='paid'` (for example a member candidate becomes a member committee).

But when creating a free membership line (with the `add.membership` wizard), the line is directly marked as paid, and this logic is not run; the statechart is not processed. Hence when creating free membership lines, I suggest to check in the statechart if a `event='paid'` transition exists and launch the creation of the following membership.

It can happen because for cdh we are adding a free subscription product, for sponsored memberships.

2023-03-27 08:52 UTC, marielejeune commented on mozaik_membership_request/wizards/add_membership.py
> +    def _create_membership_line(self, reference=None):
I added a context key to avoid some unwanted cases, for example adding a new line for a former member (the line is free hence paid, but the statechart would have created the new former_member_committee line)

2023-04-05 10:14 UTC, qgroulard requested changes
I don't understand what is 454bfa1fa434669c2e3fc99c0081840ff3c0ddda doing nor how it is related to the rest of the MR.
But I guess you know what you are doing :smiley:

2023-04-05 10:14 UTC, qgroulard commented on mozaik_membership/models/membership_tarification.py
> +                and self.env["membership.request"].browse(
Browse will always return ~True even if the record does not exist, use search instead.

2023-04-05 10:14 UTC, qgroulard commented on mozaik_sponsorship/models/membership_request.py
> +        Write the sponsor on the MR
Nit: Write the sponsor on the partner

2023-04-05 10:14 UTC, qgroulard commented on mozaik_sponsorship/models/res_partner.py
> +    godchild_ids = fields.One2many(
I would suggest to make this variable name clear that it is part of the sponsor relationship.
Either by naming it `sponsor_godchild_ids` or `sponsee_ids` (though that is not really a word, it is understandable).

2023-04-05 10:14 UTC, qgroulard commented on mozaik_sponsorship/models/membership_request.py
> +    is_sponsored_membership = fields.Boolean()
What's the point of this field and not to make it depend on `sponsor_id` ?

It makes no sense to me to be able to mark the MR `is_sponsored_membership` without any `sponsor_id` (or the opposite), yet it is currently possible.

2023-04-05 10:14 UTC, qgroulard commented on mozaik_membership_request/models/res_partner.py
> +    def _is_event_allowed_from_current_state(self, event):
This feature is already provided by scobidoo, see https://github.com/acsone/scobidoo/blob/78c110d5d5abdd53d78b9b6f1081c10e750a1c22/statechart/models/statechart_mixin.py#L227

In your case it would be `partner_id.sc_paid_allowed`

2023-04-05 10:14 UTC, qgroulard commented on mozaik_membership_request/wizards/add_membership.py
> +                res.create_following_membership(status)
Wouldn't it  be possible to mark these membership lines as paid and reuse the original workflow ?

2023-04-05 10:17 UTC, marielejeune commented on mozaik_membership_request/wizards/add_membership.py
> +                res.create_following_membership(status)
No because the move_id is mandatory in the workflow. It was my first idea but quite complicated to do

2023-04-05 11:54 UTC, marielejeune commented
> I don't understand what is [454bfa1](https://github.com/mozaik-association/mozaik/commit/454bfa1fa434669c2e3fc99c0081840ff3c0ddda) doing nor how it is related to the rest of the MR. But I guess you know what you are doing smiley

It allows to add more complex code in membership tarifications. This code can involve membership requests, if relevnt. See in ticket #67035 the solution that was proposed:


Créer un nouveau produit "Adhésion parrainage" à 0€ !! Cocher ` advance_workflow_as_paid` sur le produit.
Créer un nouveau tarif d'adhésion que l'on met tout en haut (il sera évalué en 1er). On le lie au nouveau produit, et comme code, `on met membership_request and membership_request.sponsor_id and membership_request.can_be_sponsored`. J'ai ajouté dans les variables autorisées la demande d'adhésion liée au flux courant (si cela fait du sens).
Ainsi à la validation de la demande d'adhésion, le produit sélectionné sera automatiquement "Adhésion parrainage", même si le montant reste à 0€.

2023-04-05 13:19 UTC, merged

2023-04-05 13:44 UTC, qgroulard commented on mozaik_membership_request/__manifest__.py
> +    "external_dependencies": {"python": ["openupgradelib", "sismic"]},
No need for sismic anymore

2023-04-05 13:55 UTC, marielejeune commented on mozaik_membership_request/__manifest__.py
> +    "external_dependencies": {"python": ["openupgradelib", "sismic"]},
Done on 14.0 branch