[MIG][11.0] mozaik_duplicate
mozaik-association/mozaik pull request #85
Opened 2018-07-27 14:27 UTC by acsonefho

- Migration of mozaik_duplicate
- Flake 8 (this module only)
- Pylint (this module only)
- No unit test added for this module

**Depends on the branch of Denis**

2018-08-07 11:40 UTC, Olivier-LAURENT requested changes
Cc @RobinetDenisAcsone

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/i18n/fr.po
> +#a
"a" ?

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/__init__.py
> +from . import wizard
`wizards`

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
>      _description = "Abstract Duplicate"
... Model

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
> +        result = super(AbstractDuplicate, self.sudo()).create(vals)
Hummm why sudo ?

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
> +            self_sudo.detect_and_repair_duplicate(values)
Here it would be better to use `suspend_security()`

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
> +            values = [d._get_discriminant_value() for d in self_sudo]
why to not read values without `sudo()` BEFORE the `unlink()` ?

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
>          if len(self) != 1:
`ensure_one()` is better, no reason to call this method without or with more than one object

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
> +        action.update({
Can we return in an action for the context a real dictionnary ? Would it have to stringify first ?

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
> +            'context': context,
Anyway, this replaces completely the initial context of the action... an update would be better

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
> +    def get_duplicates(self, value):
`_get_duplicates()`

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
> +    def detect_and_repair_duplicate(self, values, columns_to_read=None):
`_detect_and_repair_duplicate()`

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/wizard/allow_duplicate_view.xml
> +</odoo>
newline is missing

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/wizard/allow_duplicate_view.xml
>                      Selected duplicates are allowed. Are you sure?
Allow selected duplicates, proceed anyway?

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/wizard/allow_duplicate_wizard.py
> +    def fields_view_get(self, view_id=None, view_type='form', toolbar=False,
Is it the right method to check for prerequisites of a wizard ?

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/wizard/allow_duplicate_wizard.py
> +    _description = "Allow duplicate wizard"
duplicateS

2018-08-07 11:40 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_duplicate/wizard/allow_duplicate_wizard.py
> +        return {}
Is it a convention in V11 ?

2018-08-07 14:06 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
> +        action.update({
It's not necessary to stringify:  https://github.com/odoo/odoo/blob/11.0/addons/project/models/project.py#L938

2018-08-07 14:38 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_duplicate/wizard/allow_duplicate_wizard.py
> +        return {}
There are some example of it in odoo: https://github.com/odoo/odoo/blob/11.0/addons/account/wizard/pos_box.py#L31

But in some other wizard, they return False: https://github.com/odoo/odoo/blob/11.0/addons/stock/wizard/stock_immediate_transfer.py#L37

Which one is the best convention?

2018-08-07 15:15 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_duplicate/wizard/allow_duplicate_wizard.py
> +    def fields_view_get(self, view_id=None, view_type='form', toolbar=False,
I don't think it's the right method, but the wizard ask only a confirmation, so it's better to have the check at the opening of the form. 

Perhaps  the ```view_init``` is better? 
https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L262
https://github.com/odoo/odoo/blob/11.0/addons/crm/wizard/crm_lead_to_opportunity.py#L83

2018-08-08 12:35 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_duplicate/models/abstract_duplicate.py
> +            self_sudo.detect_and_repair_duplicate(values)
Changed, but not sure how to say to have a requirements to base_suspend_security (something special to do in the oca_dependencies.txt or somewhere else?)

2018-08-09 08:30 UTC, merged