[MIG][11.0] mozaik_coordinate
mozaik-association/mozaik pull request #86
Opened 2018-07-27 14:29 UTC by acsonefho

- Migration of mozaik_coordinate
- Flake 8 (this module only)
- Pylint (this module only)
- Make abstract unit test

**Depends on:**
- Denis branch
- mozaik_duplicate

2018-08-09 09:57 UTC, RobinetDenisAcsone commented
@Olivier-LAURENT should be good to review.
Just one question:
Francois have remove all groups and things  like ```invisible="context.get('popup')"```, at the end what have been decided for those? We will add them later or it's will be simply remove (popup)

2018-08-09 20:45 UTC, Olivier-LAURENT requested changes
Hi @RobinetDenisAcsone , some comments and questions... Thx in advance

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/coordinate_category.py
> +        size=128,
size can be removed

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/coordinate_category.py
> +    )
and track_visibility ?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +    _log_access = True
Why is it necessary ?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> -        'Unauthorized', track_visibility='onchange', default=False)
track_visibility ??

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> -    vip = fields.Boolean('VIP', track_visibility='onchange', default=False)
track_visibility ??

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +        coordinates = self.search_count(domain)
I suggest to make this search with `sudo()`... maybe a main coordinate really exists but user has no rights to find/read it ! In this case it is too bad to force `is_main=True` on the new coordinate

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +        return True
this return is useless

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +    @api.constrains('partner_id', 'is_main', 'active')
... and `coordinate_type` I suppose !

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +            return True
Why True ? return is enough or not ?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +                lambda x, c=coordinate: c.partner_id.id == x.partner_id.id and
... `c.partner_id == x.partner_id`

Moreover is it more readable by saying x=s (=~self short name) and reversing conditions (i.e. variable first): s.xxx op c.xxx

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>          return True
useless

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>      def name_get(self):
IMO: this method must call super() and involve the result only if  `is_notification==True`

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>          domain_other_active_main = self.get_target_domain(
only usefull if `is_main==True`

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +                     self.with_context(mail_create_nolog=True)).create(vals)
why this `mail_create_nolog` ?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +            raise exceptions.ValidationError(
do not raise, `_check_one_main_coordinate` will make the job !

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +            ('partner_id', 'in', partners.ids),
A stack trace is possible here if self is empty (see unlink() where the method is manually invoked unconditionally with a potential empty record set). Correct ?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>          coordinates_main = self.filtered(lambda s: s.is_main)
main_coordinates is more linguistic !

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>      def get_linked_partners(self):
is this method already useful ?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +                lambda r, p=partner: r.partner_id.id == p.id)
`s, ... s.partner_id == p`

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +        all_coordinates = self.search(domain)
Should this search() be executed with sudo() to be sure to retrieve all coordinates?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>      def search_and_update(self, target_domain, fields_to_update):
_search_and_update()

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +    def change_main_coordinate(self, partners, value):
_change_main_coordinate(...)

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>      def set_as_main(self):
_set_as_main(...)

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +        return len(results) != 0
nobody check this result... useless IMO

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>      def get_target_domain(self, partner_id, coordinate_type):
_get_target_domain(...)

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +            coords = self.search(domain, limit=limit)
idem ... sudo() ?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/tests/test_coordinate_wizard.py
> +        :return: bool
just ends your test with `return ` without returning a `bool`

Idem for all subsequent tests

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/tests/test_coordinate_wizard.py
> +        return True
just `return`

Idem for all subsequent tests

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/views/coordinate_category.xml
> +        <field name="parent_id" ref="mozaik_base.mozaik_main_menu"/>
anchor this menu somewhere in the configuration `contacts.res_partner_menu_config`

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/views/res_partner.xml
>                      <separator name="email" string="Email Coordinates"/>
these 3 separators must go into their respective module

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/change_main_coordinate.xml
> +                    <button string="Change" name="button_change_main_coordinate" type="object" class="oe_highlight" attrs="{'invisible': [('change_allowed','=', False)]}"/>
Why to have removed the `<span>...`    on which the invisible was defined ?

Now the "or" can be orphan on its left !

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/change_main_coordinate.py
> +        if not target_model:
Put this in the view_init() method

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/change_main_coordinate.py
> +        active__obj = self.env[active_model]
why this double underscore ?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/change_main_coordinate.py
> +            raise exceptions.UserError(
idem

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/change_main_coordinate.xml
> +    <!-- Change Main Coordinate Wizard on res.partner -->
remove this comment

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/change_main_coordinate.xml
> +                    <group></group>
useful ?

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/failure_editor.py
>           'CHECK(increase > 0)', '"increase" field should be a positive value'),
The "Increase by" ...

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/failure_editor.py
>      def update_failure_datas(self):
update_failure_data

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/failure_editor.py
> +    model = fields.Char(
not really useful, active_model is enough everywhere in this wizard

2018-08-09 20:45 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/wizards/failure_editor.py
> +        coordinates = self.env[self.model].browse(active_ids)
use active_model here

2018-08-10 06:42 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +    _log_access = True
It's add the ```create_uid```, ```write_uid```, ```create_date``` and ```write_date```
When ```_auto``` is True, ``` _log_access``` is True by default, so it's useless here, I remove it.

https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L337
https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L508

2018-08-10 07:18 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +            return True
It's enough

2018-08-10 07:39 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +                     self.with_context(mail_create_nolog=True)).create(vals)
I don't know from where it was added (was not there en v8), I remove it.

2018-08-10 07:54 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +            ('partner_id', 'in', partners.ids),
A check of the void record set is now done in the unlink.

2018-08-10 08:03 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>      def get_linked_partners(self):
Not for the moment, it's used in ```mozaik_email```, ```mozaik_address```, ```mozaik_membership``` and ```mozaik_phone```

2018-08-10 08:09 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +        all_coordinates = self.search(domain)
I think it will be better, changed

2018-08-10 09:06 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> -        'Unauthorized', track_visibility='onchange', default=False)
Will be added in another pr

2018-08-10 09:06 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> -    vip = fields.Boolean('VIP', track_visibility='onchange', default=False)
Will be added in another pr

2018-08-10 09:12 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
> +    _log_access = True
erratum: It's mandatory to have the view on the abstract (we show create_date).
Since it's a abstract model, _auto is false, and _log_access too.

2018-08-10 09:27 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>      def get_linked_partners(self):
It was an obsolete method to trigger compute method for related/computed fields. Correct ?

2018-08-10 11:09 UTC, merged