[MIG][11.0] mozaik_phone
mozaik-association/mozaik pull request #88
Opened 2018-07-30 14:36 UTC by acsonefho

- Migration of mozaik_phone
- Flake 8 (this module only)
- Pylint (this module only)
- Implements abstract unit test (from mozaik_coordinate)
- 1 unit test on test_res_partner, test_invalidate_partner fail due to a bug into mozaik_abstract_model

**Depends on:**
- Denis branch
- mozaik_duplicate
- mozaik_coordinate
- mozaik_email

2018-08-17 17:00 UTC, Olivier-LAURENT requested changes

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>          coordinate_type = vals.get('coordinate_type')
Is this line still useful ?

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/data/ir_config_parameter.xml
> +        <field name="key">default.country.code.phone</field>
this key has to be moved in the other repo in the `server_environment_files/default/base.conf` file

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/data/mail_message_subtype.xml
> +    <record id="phone_failure_notification" model="mail.message.subtype">
to remove as all other kind of such notification (in theory !)

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/demo/phone_coordinate.xml
> +<odoo>
please make this file as short as possible regarding your tests

This is also a general remark for all  future modules to migrate

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/demo/phone_phone.xml
> +<odoo>
id.

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/models/phone_phone.py
> +        size=50,
to remove 

General remark: all char size can be removed

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/models/phone_phone.py
>          if self.env.context.get('install_mode', False) and num[:4] == 'tbc ':
This kind of nice-to-have should be moved into the other repo

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/models/phone_phone.py
> -        return super().create(vals)
Why this form is worse ...

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/models/phone_phone.py
> +        return super(PhonePhone, self).create(vals)
... than this one ?

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/models/phone_phone.py
> +        return super(PhonePhone, self).write(vals)
same question !

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/models/res_partner.py
> +        'phone_coordinate_ids.unauthorized',
useful ?

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/models/res_partner.py
> +        'phone_coordinate_inactive_ids.active',
useful ? Maybe a former bug... Still relevant?

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/models/res_partner.py
> +            phone_coordinates = phone_coordinates.with_prefetch(self._prefetch)
`self._prefetch` or `record._prefetch` or `phone_coordinates._prefetch` ?

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/tests/test_change_phone_type.py
> +        wizard = self.wizard_obj.create({
Is a `create()` mandatory here ? A `new()` is maybe enough !

General remark for wizards

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/tests/test_res_partner.py
> +        self.assertEquals(
deprecated

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/views/phone_coordinate.xml
> +    <menuitem id="phone_coordinate_submenu" name="Phone Coordinates"
Why this rollback to menuitem ?

General remark: no use of `<menuitem/>` if possible

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/views/phone_coordinate.xml
> +            <group name="moreinfo" position="inside">
look in `mozaik_structure` how I suggest to keep this form section... as a `<page/>` of a `<notebook/>`

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/views/phone_coordinate.xml
> +                <field name="coordinate_type" groups="base.group_erp_manager"/>
IMO, not useful in the tree.

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/views/phone_phone.xml
> +                <div name="dev" class="oe_form_sheetbg" groups="base.group_erp_manager">
Put it in the notebook

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/views/res_partner.xml
> +        <field name="priority" eval="150"/>
Useful ?

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/wizards/change_main_phone.py
> +        ondelete="cascade",
not necessary for a non required M2O

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/wizards/change_main_phone.py
> +        self.change_allowed = not bool(self.phone_id == self.old_phone_id)
bool is unless

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/wizards/change_main_phone.py
> +            active_id = active_id[0]
be careful `active_id` may be a phone coordinate

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/wizards/change_main_phone.xml
> +                       on_change="onchange_phone_id(phone_id, partner_id)"/>
to remove

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/wizards/change_phone_type.xml
> +            <form string="Change Phone Type">
string can be removed

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/wizards/change_phone_type.xml
> +        <field name="view_type">form</field>
to remove

General remark: view_type can always be removed

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/wizards/failure_editor_view.xml
> +        <field name="view_type">form</field>
id.

2018-08-17 17:00 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_phone/wizards/failure_editor_view.xml
> +        <field name="multi" eval="0"/>
useful ?

2018-08-20 07:09 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_coordinate/models/abstract_coordinate.py
>          coordinate_type = vals.get('coordinate_type')
coordinate_type is used later inn the create, if the coordinate is main

2018-08-20 09:32 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_phone/models/res_partner.py
> +        'phone_coordinate_inactive_ids.active',
It doesn't seems to be useful, I remove it

2018-08-20 11:01 UTC, merged