[MIG][11.0] mozaik_abstract_model (from mozaik_base)
mozaik-association/mozaik pull request #89
Opened 2018-07-31 09:58 UTC by acsonefho

- Migration of mozaik_abstract_model (from mozaik_base)
- Flake 8 (this module only)
- Pylint (this module only)
- Unit test added for this module

- New disable_tracking_installation module: extract behaviour from mozaik_abstract_model because (I think) the behaviour is different

**Depends on the branch of Denis**

2018-08-02 14:38 UTC, Olivier-LAURENT requested changes

2018-08-02 14:38 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_abstract_model/models/mozaik_abstract_model.py
> +    def _constrain_invalidate(self):
Maybe better to name constrains methods with `_check` prefix

2018-08-02 14:38 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_abstract_model/models/mozaik_abstract_model.py
> +    def get_fields_to_update(self, mode):
It would be better to underscore this method (i.e. not useful directly from JS). Correct ?

2018-08-02 14:38 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_abstract_model/models/mozaik_abstract_model.py
> +        Note: Argument vals must be the last in the signature
Obsolete note probably

2018-08-02 14:38 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_abstract_model/models/mozaik_abstract_model.py
> +    _unicity_keys = 'N/A'
It would be better to keep `None` here as default value

2018-08-02 14:38 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_abstract_model/models/mozaik_abstract_model.py
> +        if not self._auto or self._unicity_keys == 'N/A':
Definitively if model is not `_auto`, nothing of this method can be executed !

2018-08-03 07:13 UTC, acsonefho commented on odoo/addons/mozaik_abstract_model/models/mozaik_abstract_model.py
> +        if not self._auto or self._unicity_keys == 'N/A':
Actually it's the case: it returns directly the result of the super()

2018-08-03 08:13 UTC, merged

2018-08-03 15:21 UTC, Olivier-LAURENT commented
close #79