[MIG] Migrate mozaik_address
mozaik-association/mozaik pull request #97
Opened 2018-08-23 14:44 UTC by RobinetDenisAcsone

2018-08-27 20:24 UTC, Olivier-LAURENT requested changes

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/demo/address_address.xml
> +<odoo noupdate="0">
always `=1` for demo data

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/demo/postal_coordinate.xml
> +<odoo noupdate="0">
id.

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/demo/res_city.xml
> +<odoo noupdate="0">
id.

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/models/address_address.py
> +                adrs.number or False
Would be better to say here `number = '/'.join([el for el in [number, box] if el])`   to avoid a dash at end of street if no number is provided

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/models/address_address.py
> +            country_code = self._get_default_country_code()
put this outside the loop

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/models/address_address.py
> +            for field in key_fields.keys():
`.keys()` can be omitted

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/models/address_address.py
> +        for field in values.keys():
`.keys()` can be omitted

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/models/res_city.py
> +    _unicity_keys = 'zipcode, name'
_stricto-senso_, country_id should be a part of the _unicity_keys

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/models/res_partner.py
> +                coord.partner_id.postal_coordinate_id = coord.id
remove `.id` here

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/models/res_partner.py
> +    def _compute_main_address_componant(self):
this compute method has same dependencies of the previous one with the same `search()` as point of start. Can they be merged ?

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/models/res_partner.py
> +                    coord.address_id.city_id.id or False
just `coord.address_id.city_id or False`

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/tests/test_address_address.py
> +        adr = self.model_address.create(vals)
Can a  `new()`  be sufficient ?

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/tests/test_address_address.py
> +        adr.write(vals)
and here an `update()` ?

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/views/address_address_view.xml
> +                                <field name="id"/>
id can be removed (it is in the url)

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/views/address_address_view.xml
> +                                <field name="active"/>
active must be removed because it is (or it should be) already into the toggle_active button (see other coordinate modules)

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/views/co_residency_view.xml
> +                                <field name="id"/>
same as above for the 2 fields (but keep the page and group empty)

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/views/postal_coordinate_view.xml
> +        <field name="view_type">form</field>
can be removed

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/views/postal_coordinate_view.xml
> +            <xpath expr="//div[hasclass('oe_title')]" position="inside">
`@name='title'`

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/views/res_city_view.xml
> +                                <field name="id"/>
can be removed

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/views/res_partner_view.xml
> +        <field name="inherit_id" ref="mozaik_coordinate.res_partner_form_view" />
previous inherit id is better. Doesn't work it ?

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/views/res_partner_view.xml
> +            <xpath expr="//div[hasclass('o_address_format')]" position="attributes">
Why do not use classic xpath expression @class='xxx' ?

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/wizards/allow_duplicate_wizard.py
> +        readonly=True, ondelete='cascade')
in a wzd, ondelete=cascade is only useful for required many2one fields

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/wizards/allow_duplicate_wizard.py
> +        readonly=True, ondelete='cascade')
id.

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/wizards/allow_duplicate_wizard.py
> +        ids = self.env.context.get('active_id') and \
from here until end of method, protect the code with `if 'address_id' in fields_list or 'co_residency_id' in fields_list`

2018-08-27 20:24 UTC, Olivier-LAURENT commented on odoo/addons/mozaik_address/wizards/change_co_residency_address.py
> +    message = fields.Char()
it seems it is an unused field. If yes you can remove it

2018-08-28 06:45 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_address/models/res_partner.py
> +    def _compute_main_address_componant(self):
They could be merged, but one compute stored values and the other one non-store values. I think if we merged both, stored value will be updated for nothing each time.

2018-08-28 06:46 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_address/models/res_partner.py
> +                    coord.address_id.city_id.id or False
even ```coord.address_id.city_id``` is enough I think.

2018-08-28 06:49 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_address/views/address_address_view.xml
> +                                <field name="active"/>
we aren't in a coordinate model, it's address.address

2018-08-28 06:59 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_address/views/res_partner_view.xml
> +        <field name="inherit_id" ref="mozaik_coordinate.res_partner_form_view" />
We do a ``` expr="//page[@name='coordinates']" ``` which is defined in ```mozaik_coordinate.res_partner_form_view``` (two form was defined in v8, on for ```base.view_partner_form``` and one for ```mozaik_coordinate.res_partner_form_view``` which has been merged to one)

2018-08-28 07:09 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_address/views/res_partner_view.xml
> +            <xpath expr="//div[hasclass('o_address_format')]" position="attributes">
Odoo log a warning if we use the ```@class``` expr. and say to use the hasclass.  https://www.odoo.com/documentation/11.0/reference/views.html#hasclass

2018-08-28 07:17 UTC, RobinetDenisAcsone commented on odoo/addons/mozaik_address/views/co_residency_view.xml
> +                                <field name="id"/>
True for id, but active need to be present (attrs)

2018-08-28 09:28 UTC, RobinetDenisAcsone commented
@Olivier-LAURENT changes done

2018-08-28 12:24 UTC, merged